# Generated by Django 4.1.5 on 2024-03-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulantes', '0002_alter_postulante_anio_egreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulante',
            name='anio_egreso',
            field=models.CharField(max_length=4, verbose_name='Año_egreso'),
        ),
    ]
